import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SqliteStore, migrate } from "../src/db.js";
import { runtimeMigrations } from "../src/schema.js";
import { ArtifactService } from "../src/runtime/artifacts.js";

test("artifact publication validates realpath and separates publish from read", async () => {
  const root = await mkdtemp(join(tmpdir(), "agent-home-artifact-"));
  const project = join(root, "project"); const outside = join(root, "outside.txt");
  await import("node:fs/promises").then(({ mkdir }) => mkdir(project));
  await writeFile(join(project, "ok.txt"), "safe"); await writeFile(outside, "private");
  await symlink(outside, join(project, "escape.txt"));
  const db = new SqliteStore(":memory:"); migrate(db, runtimeMigrations);
  const service = new ArtifactService(db, root);
  const capability = { publishTaskIds: ["task-1"], allowedDestinations: ["conversation-1"] };
  const artifact = await service.registerLocalArtifact({ path: join(project, "ok.txt"), taskId: "task-1", workerId: "worker-1", allowedRoots: [project], capability, maxBytes: 100 });
  const readCapability = { readableArtifactAuthorities: ["agent-home"] };
  assert.equal(artifact.filename, "ok.txt"); assert.equal(artifact.status, "AVAILABLE");
  const sendCapability = { publishTaskIds: [], allowedDestinations: ["conversation-1"] };
  assert.equal(service.authorizeOutbound(artifact.ref, { taskId: "task-1", destination: "conversation-1", capability: sendCapability }).status, "AVAILABLE");
  assert.throws(() => service.authorizeOutbound(artifact.ref, { taskId: "task-2", destination: "conversation-1", capability: sendCapability }), /ARTIFACT_OWNER_DENIED/);
  assert.throws(() => service.authorizeOutbound(artifact.ref, { taskId: "task-1", destination: "conversation-2", capability: sendCapability }), /ARTIFACT_DESTINATION_DENIED/);
  db.run("UPDATE artifacts SET status='DELETED' WHERE id=?", artifact.ref.artifactId);
  assert.throws(() => service.authorizeOutbound(artifact.ref, { taskId: "task-1", destination: "conversation-1", capability: sendCapability }), /ARTIFACT_NOT_SENDABLE/);
  db.run("UPDATE artifacts SET status='AVAILABLE',expires_at=? WHERE id=?", "2020-01-01T00:00:00.000Z", artifact.ref.artifactId);
  assert.throws(() => service.authorizeOutbound(artifact.ref, { taskId: "task-1", destination: "conversation-1", capability: sendCapability }), /ARTIFACT_EXPIRED/);
  await assert.rejects(() => service.openAuthorized(artifact.ref, { conversationId: "conversation-1", requesterId: "user-1", readCapability }), /ARTIFACT_EXPIRED/);
  assert.throws(() => service.authorizeTransfer(artifact.ref, { taskId: "task-1", destination: "conversation-1" }), /ARTIFACT_EXPIRED/);
  await assert.rejects(() => service.registerLocalArtifact({ path: join(project, "ok.txt"), taskId: "task-1", allowedRoots: [project], capability, maxBytes: 100, expiresAt: "2020-01-01T00:00:00.000Z" }), /ARTIFACT_EXPIRED/);
  assert.equal(await service.cleanupExpired("2026-01-01T00:00:00.000Z"), 1);
  assert.throws(() => service.authorizeOutbound(artifact.ref, { taskId: "task-1", destination: "conversation-1", capability: sendCapability }), /ARTIFACT_NOT_SENDABLE/);
  await assert.rejects(() => service.registerLocalArtifact({ path: join(project, "escape.txt"), taskId: "task-1", allowedRoots: [project], capability, maxBytes: 100 }), /ARTIFACT_SOURCE_ROOT_DENIED/);
  await assert.rejects(() => service.registerLocalArtifact({ path: outside, taskId: "task-2", allowedRoots: [root], capability, maxBytes: 100 }), /ARTIFACT_PUBLISH_DENIED/);
  const inbound = await service.ingestAttachment({ stream: (async function* () { yield new Uint8Array([1, 2, 3]); })(), filename: "inbound.bin", conversationId: "conversation-1", requesterId: "user-1", eventId: "event-1", maxBytes: 100 });
  assert.throws(() => service.authorizeRead(inbound.ref, { conversationId: "conversation-1", requesterId: "user-1", readCapability: { readableArtifactAuthorities: [] } }), /ARTIFACT_READ_DENIED/);
  assert.equal(service.authorizeRead(inbound.ref, { conversationId: "conversation-1", requesterId: "user-1", readCapability }).sourceRequesterId, "user-1");
  const opened = await service.openAuthorized(inbound.ref, { conversationId: "conversation-1", requesterId: "user-1", readCapability });
  const chunks: Uint8Array[] = []; for await (const chunk of opened.stream) chunks.push(chunk);
  assert.deepEqual([...Buffer.concat(chunks.map((chunk) => Buffer.from(chunk)))], [1, 2, 3]);
  const staged = await service.materializeForRead(inbound.ref, { conversationId: "conversation-1", requesterId: "user-1", readCapability }, project);
  assert.equal(await readFile(staged.path, "utf8"), "\x01\x02\x03");
  assert.match(staged.path, /inbound-artifacts/);
  assert.throws(() => service.authorizeRead(inbound.ref, { conversationId: "conversation-2", requesterId: "user-2", readCapability }), /ARTIFACT_CONVERSATION_READ_DENIED/);
  service.bindToTask(inbound.ref, { taskId: "task-1", conversationId: "conversation-1", requesterId: "user-1" });
  assert.throws(() => service.authorizeRead(inbound.ref, { conversationId: "conversation-1", requesterId: "user-1", taskId: "task-2", readCapability }), /ARTIFACT_TASK_READ_DENIED/);
  assert.ok((db.get<{ count: number }>("SELECT count(*) AS count FROM authorization_audit_events WHERE operation='artifact.publish' AND decision='ALLOW'")?.count ?? 0) >= 1);
  assert.ok((db.get<{ count: number }>("SELECT count(*) AS count FROM authorization_audit_events WHERE operation='artifact.send'")?.count ?? 0) >= 3);
  db.close(); await rm(root, { recursive: true, force: true });
});
